openapi: 3.0.0
info:
  title: Profiles
  version: '1.0'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  contact:
    name: Some Name
  description: User Profile API
servers:
  - url: 'http://localhost:3000'
paths:
  /profiles:
    get:
      summary: Get Profiles
      operationId: getUserProfilesId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/profile.v1.json
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ./models/error.v1.yaml
      description: Return list of profiles
      security:
        - apiKey: []
      tags:
        - Endpoints
  '/profile/{profileId}':
    post:
      summary: Create user profile
      operationId: createUserProfileId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/profile.v1.json
      description: Create a user profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/profile.v1.json
        description: ''
      tags:
        - Endpoints
    get:
      summary: Get user profile
      operationId: getUserProfileId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/profile.v1.json
      description: Get user profile
      requestBody:
        content:
          application/json:
            schema:
              type: integer
      tags:
        - Endpoints
    put:
      summary: Update user profile
      operationId: updateUserProfileId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/profile.v1.json
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/profile.v1.json
      description: Update user profile
      tags:
        - Endpoints
    delete:
      summary: Delete user profile
      operationId: deleteUserProfileId
      responses:
        '200':
          description: OK
      description: Delete user profile
      security:
        - apiKey: []
      requestBody:
        content:
          application/json:
            schema:
              type: integer
      tags:
        - Endpoints
    parameters:
      - schema:
          type: number
          minimum: 1
          maximum: 0
        name: profileId
        in: path
        required: true
components:
  securitySchemes:
    apiKey:
      name: API Key
      type: apiKey
      in: header
